version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./.env
    depends_on:
      - redis
      - elasticsearch
    volumes:
      - ./src:/myfoler/src

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:8.6.2
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   volumes:
  #     - ./src/global/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
  #     - ./src/global/config/mysql-connector-java-8.0.28.jar:/usr/share/logstash/mysql-connector-java-8.0.28.jar # mysql driver jar file
  #   ports:
  #     - 5000:5000
  #   depends_on:
  #     - elasticsearch

  # kibana:
  #   container_name: kibana
  #   image: docker.elastic.co/kibana/kibana:8.6.2
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - elasticsearch

volumes:
  elasticsearch-data:
    driver: local
